import { User, Product, Reel } from "./types";

export const INITIAL_USERS: User[] = [
  {
    id: "user_carlosg",
    originalId: "69a6bc8fc6a4ee00b21319ce",
    username: "carlosg",
    name: "Carlos Garcia",
    avatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=120&q=80",
    coverPhoto: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80",
    bio: "Creador oficial de contenido de moda y lifestyle en MallSocial.",
    isOnline: true,
    followers: 120,
    following: 45,
    followingUserIds: [],
    savedReelIds: [],
    isGuest: false,
  },
  {
    id: "user_davidb",
    originalId: "69a6e51cc6a4ee00b21319d3",
    username: "davidb",
    name: "David batista",
    avatar: "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?auto=format&fit=crop&w=120&q=80",
    coverPhoto: "https://images.unsplash.com/photo-1557683316-973673baf926?auto=format&fit=crop&w=800&q=80",
    bio: "Emprendedor y distribuidor de prendas exclusivas y accesorios.",
    isOnline: false,
    followers: 88,
    following: 20,
    followingUserIds: [],
    savedReelIds: [],
    isGuest: false,
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: "prod_z3lpeqsxu",
    name: "Floral Embroidery Shirts Women's V-neck Mid-sleeve Chiffon Blouse Casual Daily Office Clothing",
    price: 4.43,
    description: "Blusa casual de chifón con bordado floral y cuello en V.",
    imageUrl: "https://cf.cjdropshipping.com/quick/product/29a8a72b-8a7e-40aa-83a3-6eb83db0ee28.jpg",
    category: "Ropa de Mujer",
    sellerId: "user_carlosg",
    sellerName: "Carlos Garcia",
    sellerUsername: "carlosg",
    stock: 45,
    rating: 5,
    shippingCost: 3.5,
  },
  {
    id: "prod_5kiyvyk2i",
    name: "Women's Casual Cotton And Linen Loose Yoga Pants",
    price: 3.32,
    description: "Pantalones holgados de algodón y lino para yoga y uso diario.",
    imageUrl: "https://cf.cjdropshipping.com/quick/product/ea3478d1-c167-422a-a9a3-5cce9e6587c4.jpg",
    category: "Deporte y Yoga",
    sellerId: "user_carlosg",
    sellerName: "Carlos Garcia",
    sellerUsername: "carlosg",
    stock: 60,
    rating: 5,
    shippingCost: 2.8,
  },
  {
    id: "prod_cbfp8fcnv",
    name: "Women's Sexy Deep V-neck Leopard Print Suspender Top",
    price: 1.9,
    description: "Top estampado de leopardo con escote en V pronunciado.",
    imageUrl: "https://cf.cjdropshipping.com/quick/product/3a59d997-76b2-4d13-a449-3ecff7f3693e.jpg",
    category: "Moda y Tendencias",
    sellerId: "user_carlosg",
    sellerName: "Carlos Garcia",
    sellerUsername: "carlosg",
    stock: 35,
    rating: 4.8,
    shippingCost: 2.5,
  },
  {
    id: "prod_zpkdzg8zt",
    name: "Men's Solid Color Business Casual Suit Jacket Velvet Lapel",
    price: 12.5,
    description: "Chaqueta de traje casual para hombres con solapa de terciopelo elegante.",
    imageUrl: "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?auto=format&fit=crop&w=600&q=80",
    category: "Moda Hombre",
    sellerId: "user_davidb",
    sellerName: "David batista",
    sellerUsername: "davidb",
    stock: 20,
    rating: 5,
    shippingCost: 4.0,
  },
];

export const INITIAL_REELS: Reel[] = [
  {
    id: "reel_a8lfpirw8",
    creatorId: "user_carlosg",
    creatorName: "Carlos Garcia",
    creatorUsername: "carlosg",
    creatorAvatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=120&q=80",
    videoUrl: "https://storage.googleapis.com/mall-1bucket/publicaciones/1788542551812-shwsdr3z4-110888.mp4",
    thumbnailUrl: "https://cf.cjdropshipping.com/quick/product/29a8a72b-8a7e-40aa-83a3-6eb83db0ee28.jpg",
    description: "¡Nuevo outfit disponible en la tienda! Chifón floral elegante ✨",
    caption: "¡Nuevo outfit disponible en la tienda! Chifón floral elegante ✨",
    likes: 84,
    comments: [],
    shares: 12,
    saves: 34,
    views: 310,
    productId: "prod_z3lpeqsxu",
    type: "video",
  },
  {
    id: "reel_zjr8pk2kv",
    creatorId: "user_carlosg",
    creatorName: "Carlos Garcia",
    creatorUsername: "carlosg",
    creatorAvatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=120&q=80",
    videoUrl: "https://storage.googleapis.com/mall-1bucket/publicaciones/1788544795023-4chpc54zb-95700.mp4",
    thumbnailUrl: "https://cf.cjdropshipping.com/quick/product/ea3478d1-c167-422a-a9a3-5cce9e6587c4.jpg",
    description: "Pantalones de yoga súper cómodos para esta temporada 🌿",
    caption: "Pantalones de yoga súper cómodos para esta temporada 🌿",
    likes: 62,
    comments: [],
    shares: 9,
    saves: 19,
    views: 240,
    productId: "prod_5kiyvyk2i",
    type: "video",
  },
  {
    id: "reel_yxloewhaf",
    creatorId: "user_carlosg",
    creatorName: "Carlos Garcia",
    creatorUsername: "carlosg",
    creatorAvatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=120&q=80",
    videoUrl: "https://storage.googleapis.com/mall-1bucket/publicaciones/1788545680024-ejdo6nfvd-cjVideos_(9).mp4",
    thumbnailUrl: "https://cf.cjdropshipping.com/quick/product/3a59d997-76b2-4d13-a449-3ecff7f3693e.jpg",
    description: "Estilo casual y fresco para el fin de semana ☀️",
    caption: "Estilo casual y fresco para el fin de semana ☀️",
    likes: 95,
    comments: [],
    shares: 18,
    saves: 42,
    views: 450,
    productId: "prod_cbfp8fcnv",
    type: "video",
  },
  {
    id: "reel_clzukwc27",
    creatorId: "user_davidb",
    creatorName: "David batista",
    creatorUsername: "davidb",
    creatorAvatar: "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?auto=format&fit=crop&w=120&q=80",
    videoUrl: "https://storage.googleapis.com/mall-1bucket/publicaciones/1788546732009-pjsf4cel5-9044abf6a2ac71f19a4e4531859c0402.mp4",
    thumbnailUrl: "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?auto=format&fit=crop&w=600&q=80",
    description: "Chaqueta formal con solapa de terciopelo en detalle 💼",
    caption: "Chaqueta formal con solapa de terciopelo en detalle 💼",
    likes: 110,
    comments: [],
    shares: 25,
    saves: 55,
    views: 520,
    productId: "prod_zpkdzg8zt",
    type: "video",
  },
  {
    id: "reel_46zz7vbox",
    creatorId: "user_davidb",
    creatorName: "David batista",
    creatorUsername: "davidb",
    creatorAvatar: "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?auto=format&fit=crop&w=120&q=80",
    videoUrl: "https://storage.googleapis.com/mall-1bucket/publicaciones/1788546983633-hbhhk10dk-cjVideos_(3).mp4",
    thumbnailUrl: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=600&q=80",
    description: "Moda de negocios casual para toda ocasión 🔥",
    caption: "Moda de negocios casual para toda ocasión 🔥",
    likes: 47,
    comments: [],
    shares: 5,
    saves: 14,
    views: 180,
    type: "video",
  },
  {
    id: "reel_e4c816xs1",
    creatorId: "user_davidb",
    creatorName: "David batista",
    creatorUsername: "davidb",
    creatorAvatar: "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?auto=format&fit=crop&w=120&q=80",
    videoUrl: "https://storage.googleapis.com/mall-1bucket/publicaciones/1788547045520-rcb7sdchg-cjVideos_(1).mp4",
    thumbnailUrl: "https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?auto=format&fit=crop&w=600&q=80",
    description: "Prendas cómodas con envío rápido a toda la región 📦",
    caption: "Prendas cómodas con envío rápido a toda la región 📦",
    likes: 73,
    comments: [],
    shares: 11,
    saves: 29,
    views: 290,
    type: "video",
  },
  {
    id: "reel_qjqcm6wsj",
    creatorId: "user_davidb",
    creatorName: "David batista",
    creatorUsername: "davidb",
    creatorAvatar: "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?auto=format&fit=crop&w=120&q=80",
    videoUrl: "https://storage.googleapis.com/mall-1bucket/publicaciones/1788547136113-p2v3gyjgc-cjVideos_(2).mp4",
    thumbnailUrl: "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=600&q=80",
    description: "¡Aprovecha los descuentos en tienda! 🛍️",
    caption: "¡Aprovecha los descuentos en tienda! 🛍️",
    likes: 88,
    comments: [],
    shares: 14,
    saves: 38,
    views: 380,
    type: "video",
  },
  {
    id: "reel_h9bcfbvte",
    creatorId: "user_carlosg",
    creatorName: "Carlos Garcia",
    creatorUsername: "carlosg",
    creatorAvatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=120&q=80",
    videoUrl: "https://storage.googleapis.com/mall-1bucket/publicaciones/1788653076281-bamvws2x9-112088.mp4",
    thumbnailUrl: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=600&q=80",
    description: "Tendencias de moda femenina 2026 en MallSocial ✨",
    caption: "Tendencias de moda femenina 2026 en MallSocial ✨",
    likes: 132,
    comments: [],
    shares: 31,
    saves: 60,
    views: 610,
    type: "video",
  },
];
