import React, { useState, useEffect, useRef } from "react";
import { User as UserIcon, ShieldCheck, UserPlus, ArrowRight, Sparkles, Check, Play, ShoppingBag, MessageSquare, Radio, Mail } from "lucide-react";
import { User } from "../../types";
import { apiFetch } from "../../config";
import { sessionState } from "../../utils/sessionState";

interface LoginViewProps {
  onLoginSuccess: (user: User) => void;
  onRefreshUsers: () => void;
  users: User[];
  currentUser?: User | null;
  initialTab?: "login" | "register";
  restrictionNotice?: string;
}

const PRESET_AVATARS = [
  "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=120&q=80",
  "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=120&q=80",
  "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=120&q=80",
  "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=120&q=80",
];

const PRESET_COVERS = [
  "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80",
  "https://images.unsplash.com/photo-1557683316-973673baf926?auto=format&fit=crop&w=800&q=80",
  "https://images.unsplash.com/photo-1579546929518-9e396f3cc809?auto=format&fit=crop&w=800&q=80",
];

export default function LoginView({
  onLoginSuccess,
  onRefreshUsers,
  users,
  currentUser,
  initialTab,
  restrictionNotice
}: LoginViewProps) {
  const [activeTab, setActiveTab] = useState<"login" | "register">(() => {
    if (initialTab) return initialTab;
    if (currentUser?.isGuest || currentUser?.username === "invitado") return "register";
    return "login";
  });
  
  // Login State: strictly Correo Electrónico and Contraseña
  const [emailInput, setEmailInput] = useState("");
  const [passwordInput, setPasswordInput] = useState("");
  const [loginError, setLoginError] = useState("");
  const [isLoggingIn, setIsLoggingIn] = useState(false);

  // Register State: strictly Nombre Completo, Correo Electrónico, and Contraseña
  const [regName, setRegName] = useState("");
  const [regPassword, setRegPassword] = useState("");
  const [regEmail, setRegEmail] = useState("");
  const [registerError, setRegisterError] = useState("");
  const [isRegistering, setIsRegistering] = useState(false);

  // Auto-assigned username generated by the app when the guest arrived
  const assignedUsername =
    (currentUser?.username && currentUser.username !== "invitado" && currentUser.username !== "current_user" && currentUser.username !== "usuario_actual")
      ? currentUser.username
      : (sessionState.getUser()?.username && sessionState.getUser()?.username !== "invitado" && sessionState.getUser()?.username !== "current_user")
      ? sessionState.getUser()!.username
      : "";

  useEffect(() => {
    onRefreshUsers();
  }, []);

  const handleLogin = async (e: React.FormEvent) => {
    if (e) e.preventDefault();
    if (isLoggingIn) return;
    setLoginError("");
    
    const cleanEmail = emailInput.trim().toLowerCase();
    if (!cleanEmail) {
      setLoginError("Por favor ingresa tu correo electrónico.");
      return;
    }

    if (!cleanEmail.includes("@")) {
      setLoginError("Por favor ingresa un correo electrónico válido.");
      return;
    }

    if (!passwordInput.trim()) {
      setLoginError("Por favor ingresa tu contraseña.");
      return;
    }

    setIsLoggingIn(true);

    try {
      const response = await apiFetch("/api/users/current/switch", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ targetUsername: cleanEmail, password: passwordInput.trim() }),
      });
      
      const data = await response.json();
      if (response.ok && data.success) {
        sessionState.setAuthenticated(true);
        sessionState.setUsername(data.user?.username || cleanEmail);
        
        sessionState.setUser(data.user);
        onLoginSuccess(data.user);
      } else {
        setLoginError(data.error || "El correo electrónico o la contraseña son incorrectos. Verifica tus datos.");
      }
    } catch (err) {
      console.error("Login error:", err);
      setLoginError("Error de conexión. Inténtalo de nuevo.");
    } finally {
      setIsLoggingIn(false);
    }
  };

  const registeringRef = useRef(false);

  const handleRegister = async (e: React.FormEvent) => {
    e.preventDefault();
    if (isRegistering || registeringRef.current) return;
    registeringRef.current = true;
    setRegisterError("");

    if (!regName.trim()) {
      setRegisterError("El nombre completo es obligatorio.");
      registeringRef.current = false;
      return;
    }

    if (!regEmail.trim()) {
      setRegisterError("El correo electrónico es obligatorio.");
      registeringRef.current = false;
      return;
    }

    if (!regPassword.trim()) {
      setRegisterError("La contraseña es obligatoria.");
      registeringRef.current = false;
      return;
    }

    setIsRegistering(true);

    try {
      const response = await apiFetch("/api/users/register", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          name: regName.trim(),
          username: assignedUsername || undefined,
          email: regEmail.trim(),
          password: regPassword.trim(),
          bio: "Miembro de la plataforma",
          avatar: PRESET_AVATARS[0],
          coverPhoto: PRESET_COVERS[0],
        }),
      });

      const data = await response.json();
      if (response.ok && data.success) {
        // Automatically log in using the returned user session
        sessionState.setAuthenticated(true);
        sessionState.setUsername(data.user?.username || assignedUsername);
        
        sessionState.setUser(data.user);
        onRefreshUsers();
        onLoginSuccess(data.user);
      } else {
        setRegisterError(data.error || "Error al registrar el usuario.");
      }
    } catch (err) {
      console.error("Registration error:", err);
      setRegisterError("Error de conexión. Inténtalo de nuevo.");
    } finally {
      setIsRegistering(false);
      registeringRef.current = false;
    }
  };

  return (
    <div
      className="w-full max-w-full min-h-screen bg-white text-slate-900 flex flex-col justify-start md:justify-center items-center px-3 sm:px-6 relative overflow-x-hidden overflow-y-auto no-scrollbar"
      id="auth-root-view"
      style={{
        scrollbarWidth: 'none',
        msOverflowStyle: 'none',
        paddingTop: 'calc(env(safe-area-inset-top, 0px) + 12px)',
        paddingBottom: 'calc(44px + env(safe-area-inset-bottom, 0px) + 12px)'
      }}
    >
      {/* Main Authentication Card */}
      <div className="w-full max-w-4xl bg-white border border-slate-200 rounded-2xl sm:rounded-3xl shadow-xl overflow-hidden flex flex-col md:flex-row z-10 min-h-[500px] mb-0">
        
        {/* Left Side: Brand Promo Panel */}
        <div className="md:w-5/12 bg-slate-50 p-6 sm:p-8 flex flex-col justify-between text-slate-900 relative overflow-hidden shrink-0 border-b md:border-b-0 md:border-r border-slate-200">
          <div className="absolute inset-0 bg-gradient-to-tr from-amber-500/10 via-amber-100/20 to-white opacity-90 z-0" />
          
          <div className="relative z-10">
            {/* Logo */}
            <div className="flex items-center space-x-2.5 bg-amber-500/15 border border-amber-500/30 px-3.5 py-1.5 rounded-full w-fit">
              <span className="w-2 h-2 rounded-full bg-amber-500 animate-pulse" />
              <span className="text-[10px] font-mono font-bold tracking-wider uppercase text-amber-700">Plataforma Social</span>
            </div>
            
            <h1 className="font-display font-black text-2xl mt-6 leading-tight tracking-tight text-slate-900">
              Sintoniza, Chatea, <span className="text-amber-500">Vende</span>
            </h1>
            <p className="text-xs text-slate-600 mt-3 leading-relaxed">
              Únete a la nueva era del comercio interactivo. Comparte reels de tus productos, interactúa en vivo y gestiona tu propio catálogo.
            </p>
          </div>

          {/* Benefits Bullet Points */}
          <div className="space-y-4 my-6 md:my-0 relative z-10">
            <div className="flex items-start space-x-3">
              <div className="p-1.5 bg-amber-500/15 rounded-lg text-amber-600 shrink-0 border border-amber-500/25">
                <Play className="w-3.5 h-3.5 fill-current" />
              </div>
              <div>
                <h4 className="text-xs font-bold text-slate-900">Reels de Compra Directa</h4>
                <p className="text-[10px] text-slate-500 leading-normal">Vincula tus productos en videos interactivos y vende con un clic.</p>
              </div>
            </div>

            <div className="flex items-start space-x-3">
              <div className="p-1.5 bg-amber-500/15 rounded-lg text-amber-600 shrink-0 border border-amber-500/25">
                <ShoppingBag className="w-3.5 h-3.5" />
              </div>
              <div>
                <h4 className="text-xs font-bold text-slate-900">Catálogo Completo</h4>
                <p className="text-[10px] text-slate-500 leading-normal">Publica en múltiples categorías con soporte multimedia.</p>
              </div>
            </div>

            <div className="flex items-start space-x-3">
              <div className="p-1.5 bg-amber-500/15 rounded-lg text-amber-600 shrink-0 border border-amber-500/25">
                <MessageSquare className="w-3.5 h-3.5" />
              </div>
              <div>
                <h4 className="text-xs font-bold text-slate-900">Mensajería en Vivo</h4>
                <p className="text-[10px] text-slate-500 leading-normal">Chatea en tiempo real con compradores y otros creadores.</p>
              </div>
            </div>
          </div>

        </div>

        {/* Right Side: Authentication Forms */}
        <div className="flex-1 p-6 md:p-8 flex flex-col justify-between bg-white">
          <div>
            {/* Tab Swapping Header */}
            <div className="flex border-b border-slate-200 pb-3 mb-6">
              <button
                onClick={() => { setActiveTab("login"); setLoginError(""); }}
                className={`text-xs font-bold px-4 py-2 rounded-xl transition-all mr-2 flex items-center space-x-2 cursor-pointer ${
                  activeTab === "login"
                    ? "bg-amber-500 text-slate-950 shadow-xs"
                    : "text-slate-500 hover:text-slate-900 hover:bg-slate-100"
                }`}
                id="btn-tab-login"
              >
                <span>Iniciar Sesión</span>
              </button>
              <button
                onClick={() => { setActiveTab("register"); setRegisterError(""); }}
                className={`text-xs font-bold px-4 py-2 rounded-xl transition-all flex items-center space-x-2 cursor-pointer ${
                  activeTab === "register"
                    ? "bg-amber-500 text-slate-950 shadow-xs"
                    : "text-slate-500 hover:text-slate-900 hover:bg-slate-100"
                }`}
                id="btn-tab-register"
              >
                <UserPlus className="w-3.5 h-3.5" />
                <span>Crear Cuenta</span>
              </button>
            </div>

            {/* TAB CONTENT: LOGIN */}
            {activeTab === "login" && (
              <div className="space-y-5">
                <div>
                  <h2 className="text-lg font-extrabold text-slate-900 tracking-tight">Iniciar Sesión</h2>
                  <p className="text-xs text-slate-500 mt-1">Ingresa con tu correo electrónico y la contraseña que configuraste al momento del registro.</p>
                </div>

                <form onSubmit={handleLogin} className="space-y-4">
                  <div>
                    <label className="block text-[10px] font-bold text-slate-600 uppercase tracking-wider mb-1.5">Correo Electrónico</label>
                    <div className="relative">
                      <Mail className="w-4 h-4 text-slate-400 absolute left-4 top-1/2 -translate-y-1/2" />
                      <input
                        type="email"
                        placeholder="ejemplo@correo.com"
                        value={emailInput}
                        onChange={(e) => setEmailInput(e.target.value)}
                        className="w-full bg-slate-50 text-slate-900 placeholder-slate-400 rounded-xl pl-11 pr-4 py-3 text-xs border border-slate-200 focus:bg-white focus:outline-none focus:border-amber-500 focus:ring-1 focus:ring-amber-500 transition-colors"
                        id="login-email-input"
                        required
                      />
                    </div>
                  </div>

                  <div>
                    <label className="block text-[10px] font-bold text-slate-600 uppercase tracking-wider mb-1.5">Contraseña</label>
                    <input
                      type="password"
                      placeholder="Tu contraseña registrada"
                      value={passwordInput}
                      onChange={(e) => setPasswordInput(e.target.value)}
                      className="w-full bg-slate-50 text-slate-900 placeholder-slate-400 rounded-xl px-4 py-3 text-xs border border-slate-200 focus:bg-white focus:outline-none focus:border-amber-500 focus:ring-1 focus:ring-amber-500 transition-colors"
                      id="login-password-input"
                      required
                    />
                  </div>

                  {loginError && (
                    <div className="text-[11px] text-rose-600 bg-rose-50 border border-rose-200 px-3.5 py-2.5 rounded-xl font-medium">
                      ⚠️ {loginError}
                    </div>
                  )}

                  <button
                    type="submit"
                    disabled={isLoggingIn}
                    className="w-full py-3 px-4 bg-amber-500 hover:bg-amber-600 disabled:bg-slate-200 text-slate-950 font-bold rounded-xl text-xs transition-all flex items-center justify-center space-x-2 cursor-pointer shadow-md shadow-amber-500/15"
                    id="login-submit-btn"
                  >
                    {isLoggingIn ? (
                      <span className="w-4 h-4 border-2 border-slate-950 border-t-transparent rounded-full animate-spin"></span>
                    ) : (
                      <>
                        <span>Ingresar</span>
                        <ArrowRight className="w-4 h-4" />
                      </>
                    )}
                  </button>
                </form>
              </div>
            )}

            {/* TAB CONTENT: REGISTER */}
            {activeTab === "register" && (
              <div className="space-y-4 pb-4">
                {restrictionNotice && (
                  <div className="bg-amber-500/10 border border-amber-500/30 rounded-xl p-3 flex items-start space-x-2.5 text-amber-950">
                    <ShieldCheck className="w-4 h-4 text-amber-600 shrink-0 mt-0.5" />
                    <div>
                      <h4 className="text-xs font-bold text-slate-900">Acceso a Perfil Restringido</h4>
                      <p className="text-[11px] text-slate-600 mt-0.5 leading-snug">
                        {restrictionNotice}
                      </p>
                    </div>
                  </div>
                )}

                <div>
                  <h2 className="text-lg font-extrabold text-slate-900 tracking-tight">Crea tu Cuenta</h2>
                  <p className="text-xs text-slate-500 mt-1">
                    Regístrate para acceder a tu perfil, publicaciones guardadas, compras e interacciones.
                  </p>
                </div>

                <form onSubmit={handleRegister} className="space-y-3">
                  <div>
                    <label className="block text-[10px] font-bold text-slate-600 uppercase tracking-wider mb-1">Nombre Completo</label>
                    <input
                      type="text"
                      placeholder="Ej. Juan Pérez"
                      value={regName}
                      onChange={(e) => setRegName(e.target.value)}
                      className="w-full bg-slate-50 text-slate-900 placeholder-slate-400 rounded-xl px-4 py-2.5 text-xs border border-slate-200 focus:bg-white focus:outline-none focus:border-amber-500 transition-colors"
                      id="reg-name-input"
                      required
                    />
                  </div>

                  <div>
                    <label className="block text-[10px] font-bold text-slate-600 uppercase tracking-wider mb-1">Correo Electrónico</label>
                    <input
                      type="email"
                      placeholder="ejemplo@correo.com"
                      value={regEmail}
                      onChange={(e) => setRegEmail(e.target.value)}
                      className="w-full bg-slate-50 text-slate-900 placeholder-slate-400 rounded-xl px-4 py-2.5 text-xs border border-slate-200 focus:bg-white focus:outline-none focus:border-amber-500 transition-colors"
                      id="reg-email-input"
                      required
                    />
                  </div>

                  <div>
                    <label className="block text-[10px] font-bold text-slate-600 uppercase tracking-wider mb-1">Contraseña</label>
                    <input
                      type="password"
                      placeholder="Crea una contraseña segura"
                      value={regPassword}
                      onChange={(e) => setRegPassword(e.target.value)}
                      className="w-full bg-slate-50 text-slate-900 placeholder-slate-400 rounded-xl px-4 py-2.5 text-xs border border-slate-200 focus:bg-white focus:outline-none focus:border-amber-500 transition-colors"
                      id="reg-password-input"
                      required
                    />
                  </div>

                  {assignedUsername ? (
                    <div className="bg-slate-50 border border-slate-200 rounded-xl px-3.5 py-2.5 flex items-center justify-between">
                      <span className="text-[11px] text-slate-600 font-medium">Nombre de usuario asignado:</span>
                      <span className="font-mono font-bold text-amber-600 text-xs">@{assignedUsername}</span>
                    </div>
                  ) : null}
                  <p className="text-[10px] text-slate-400 leading-tight">
                    Podrás personalizar tu nombre de usuario, biografía y foto de perfil en la página de Configuración cuando quieras.
                  </p>

                  {registerError && (
                    <div className="text-[11px] text-rose-600 bg-rose-50 border border-rose-200 px-3.5 py-2 rounded-xl font-medium">
                      ⚠️ {registerError}
                    </div>
                  )}

                  <button
                    type="submit"
                    disabled={isRegistering}
                    className="w-full py-2.5 px-4 bg-amber-500 hover:bg-amber-600 disabled:bg-slate-200 text-slate-950 font-bold rounded-xl text-xs transition-all flex items-center justify-center space-x-2 cursor-pointer shadow-md shadow-amber-500/15"
                    id="register-submit-btn"
                  >
                    {isRegistering ? (
                      <span className="w-4 h-4 border-2 border-slate-950 border-t-transparent rounded-full animate-spin"></span>
                    ) : (
                      <>
                        <span>Crear Cuenta y Continuar</span>
                        <Sparkles className="w-4 h-4" />
                      </>
                    )}
                  </button>
                </form>
              </div>
            )}
          </div>

        </div>

      </div>
    </div>
  );
}
